# -*- coding: utf-8 -*-
"""Welcome to Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb

# New section
1. What is NumPy, and why is it widely used in Python

NumPy (Numerical Python) is a Python library used for numerical computing and working with arrays.

Why it is widely used

Fast operations on large datasets

Supports multidimensional arrays

Provides mathematical functions (mean, std, linear algebra)

Used as the base library for Pandas, SciPy, and machine learning tools

Example

import numpy as np
a = np.array([1,2,3])
print(a.mean())
2. How does broadcasting work in NumPy

Broadcasting allows NumPy to perform operations on arrays of different shapes without explicitly reshaping them.

Example

import numpy as np
a = np.array([1,2,3])
b = 5
print(a + b)

Output

[6 7 8]

NumPy automatically expands b to match the array size.

3. What is a Pandas DataFrame

A DataFrame is a 2-dimensional labeled data structure in Pandas similar to an Excel table or SQL table.

Features

Rows and columns

Different data types

Easy data manipulation

Example

import pandas as pd

data = {'Name':['Amit','Rahul'], 'Age':[25,27]}
df = pd.DataFrame(data)
4. Explain the use of the groupby() method in Pandas

groupby() is used to split data into groups based on a column and perform aggregation.

Example

df.groupby("Department")["Salary"].mean()

Use cases

Average sales per region

Total revenue per product

Count of employees per department

5. Why is Seaborn preferred for statistical visualizations

Seaborn is built on top of Matplotlib and is preferred because:

Better statistical plots

More attractive default themes

Works directly with Pandas DataFrames

Easy correlation and distribution plots

6. Differences between NumPy arrays and Python lists
Feature	NumPy Array	Python List
Speed	Faster	Slower
Data type	Same type	Mixed types
Memory	Efficient	More memory
Mathematical operations	Built-in	Need loops

Example

np.array([1,2,3]) * 2
7. What is a heatmap and when should it be used

A heatmap is a graphical representation where values are represented using colors.

Common uses

Correlation matrix

Pattern detection

Data density visualization

Example

import seaborn as sns
sns.heatmap(data.corr())
8. What does “vectorized operation” mean in NumPy

Vectorization means performing operations on entire arrays without loops.

Example

Without vectorization

for i in arr:
    i = i*2

Vectorized

arr * 2

This makes computation much faster.

9. How does Matplotlib differ from Plotly
Feature	Matplotlib	Plotly
Type	Static plots	Interactive plots
Usage	Research and analysis	Dashboards and web apps
Interactivity	Limited	Zoom, hover, filter
10. Significance of hierarchical indexing in Pandas

Hierarchical indexing (MultiIndex) allows multiple levels of indexing on rows or columns.

Example

Country → State → City

Benefits

Work with high-dimensional data

More flexible data representation

11. Role of Seaborn’s pairplot() function

pairplot() shows relationships between multiple variables.

It creates:

Scatter plots

Distribution plots

Correlation patterns

Example

sns.pairplot(data)
12. Purpose of describe() function in Pandas

describe() gives statistical summary of data.

It returns:

count

mean

standard deviation

min

max

quartiles

Example

df.describe()
13. Why handling missing data is important in Pandas

Missing values can cause:

Wrong analysis

Errors in machine learning models

Incorrect statistics

Pandas provides functions like:

dropna()

fillna()

14. Benefits of using Plotly for data visualization

Plotly advantages:

Interactive charts

Zoom and hover tools

Web-based dashboards

Integration with Dash for web apps

15. How NumPy handles multidimensional arrays

NumPy uses ndarray objects that can store data in multiple dimensions.

Examples

1D array

[1,2,3]

2D array

[[1,2],
 [3,4]]

3D arrays also possible.

16. Role of Bokeh in data visualization

Bokeh is used for interactive web visualizations.

Features:

Real-time dashboards

Interactive plots

Browser-based visualizations

17. Difference between apply() and map() in Pandas
Function	Usage
map()	Works on Series
apply()	Works on Series or DataFrame

Example

df["Age"].map(lambda x: x+1)
18. Some advanced features of NumPy

Linear algebra (numpy.linalg)

Random number generation

Fourier transforms

Broadcasting

Memory-efficient arrays

19. How Pandas simplifies time series analysis

Pandas provides tools for:

Date indexing

Resampling data

Time shifting

Rolling statistics

Example

df.resample('M').mean()
20. Role of pivot table in Pandas

A pivot table summarizes data by aggregating values based on categories.

Example

pd.pivot_table(df, values='Sales', index='Region', columns='Product')
21. Why NumPy array slicing is faster than list slicing

Because:

NumPy arrays store data in contiguous memory

Operations are executed in C language internally

Avoids Python loops

22. Common use cases for Seaborn

Correlation heatmaps

Distribution analysis

Regression plots

Category comparisons

Statistical data exploration

Example

sns.boxplot(x="gender", y="salary", data=df)
"""

Q1.
import numpy as np


arr = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])

row_sum = arr.sum(axis=1)

print(row_sum)

Q2.
import pandas as pd

data = {
    "Name": ["Amit","Rahul","Riya","Neha"],
    "Age": [23,25,24,22],
    "Salary": [40000,50000,45000,42000]
}

df = pd.DataFrame(data)

mean_salary = df["Salary"].mean()

print(mean_salary)

Q3.
import matplotlib.pyplot as plt

x = [1,2,3,4,5]
y = [10,15,13,17,20]

plt.scatter(x,y)

plt.xlabel("X values")
plt.ylabel("Y values")
plt.title("Scatter Plot Example")

plt.show()

Q4.
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

data = {
    "Sales":[200,220,250,270,300],
    "Marketing":[50,60,65,70,80],
    "Profit":[20,25,30,35,40]
}

df = pd.DataFrame(data)

corr = df.corr()

sns.heatmap(corr, annot=True)

plt.title("Correlation Heatmap")
plt.show()

Q5.
import plotly.express as px
import pandas as pd

data = {
    "Product":["A","B","C","D"],
    "Sales":[100,150,200,130]
}

df = pd.DataFrame(data)

fig = px.bar(df, x="Product", y="Sales",
             title="Product Sales")

fig.show()

Q6.
import pandas as pd

data = {
    "Name": ["Amit", "Rahul", "Neha"],
    "Salary": [40000, 50000, 45000]
}

df = pd.DataFrame(data)

df["Bonus"] = df["Salary"] * 0.10

print(df)

Q7.
import numpy as np

a = np.array([1,2,3])
b = np.array([4,5,6])

result = a * b

print(result)

Q8.
import matplotlib.pyplot as plt

x = [1,2,3,4]

y1 = [10,20,30,40]
y2 = [15,25,35,45]

plt.plot(x, y1, label="Sales 2023")
plt.plot(x, y2, label="Sales 2024")

plt.xlabel("Quarter")
plt.ylabel("Sales")
plt.title("Sales Comparison")

plt.legend()
plt.show()

Q9.
import pandas as pd

data = {
    "Name": ["Amit","Rahul","Neha","Riya"],
    "Marks": [60,85,70,90]
}

df = pd.DataFrame(data)

filtered = df[df["Marks"] > 75]

print(filtered)

Q10.
import seaborn as sns
import matplotlib.pyplot as plt

data = [10,12,15,18,20,20,22,25,30,35]

sns.histplot(data, bins=5)

plt.title("Distribution of Values")
plt.show()

Q11.
import numpy as np

A = np.array([[1,2],
              [3,4]])

B = np.array([[5,6],
              [7,8]])

result = np.dot(A, B)

print(result)

Q12.
import pandas as pd

df = pd.read_csv("data.csv")

print(df.head())